### ISSUE TITLE
ubuntu 20.04 64bit 显示网络异常，无法登录

### ISSUE THREAD

**Issue by kelebujiabing** [ZetaoYang/netease-cloud-music-appimage#10]
![Screenshot from 2023-12-05 16-36-03](https://github.com/holazt/netease-cloud-music-appimage/assets/10735902/e7711be9-bb52-4e4c-9f00-81e4de4a12ee)

**Comment by kelebujiabing** [comment]
kele@XPS8950:~$ cat /proc/version
Linux version 5.15.0-46-generic (buildd@lcy02-amd64-007) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022

**Comment by holazt** [comment]
从 2023 年 8 月份开始起，有 deepin 用户就报告 Linux 端登录不了了。见 
- https://bbs.deepin.org/post/260815
- https://bbs.deepin.org/post/261096
- https://bbs.deepin.org/post/261469
- https://www.cnblogs.com/SendBoringBackToNoWhere/p/17633696.html
- https://aur.archlinux.org/packages/netease-cloud-music

如果还无法登录，就试试其他第三方的桌面端吧，这个问题应该是网易那边接口更新了，不再兼容旧版 Linux 端了。

**Comment by kelebujiabing** [comment]
非常感谢
