### ISSUE TITLE
无法显示在系统托盘

### ISSUE THREAD

**Issue by amazingfate** [ZetaoYang/netease-cloud-music-appimage#2]
https://bbs.archlinuxcn.org/viewtopic.php?id=5691
似乎需要加一个环境变量

**Comment by holazt** [comment]
感谢，我晚上试试，测一测。

**Comment by holazt** [comment]
@amazingfate 我试过了，无论在 Appimage 内部的 desktop 文件，还是外部的 desktop 文件，`Exec=env XDG_CURRENT_DESKTOP=DDE netease-cloud-music %U`都没有效果。(Fedora 30 Gnome 环境)

**Comment by amazingfate** [comment]
的确很奇怪，我现在用从官网下ubuntu的deb，XDG_CURRENT_DESKTOP=Unity启动可以显示在托盘托盘（opensuse tumbleweed）

**Comment by holazt** [comment]
@amazingfate  Gnome 会在顶部栏显示播放控件，如下图：
![Snipaste_2019-07-13_13-55-14](https://user-images.githubusercontent.com/10769951/61167785-f1eb5800-a575-11e9-870c-f886613630cb.png)

**Comment by amazingfate** [comment]
看来系统托盘是个标准的接口，各个桌面环境都会有自己的实现，不过Gnome弄得也太简陋了
