### ISSUE TITLE
最新版本在opensuse leap 15.1中显示libm.so和libc.so版本低于2.27.

### ISSUE THREAD

**Issue by fenglelyng** [ZetaoYang/netease-cloud-music-appimage#3]
最新版本在opensuse leap 15.1中显示libm.so和libc.so版本低于2.27.有什么办法吗

**Comment by fenglelyng** [comment]
而且我了解到，并不是程序本身需要2.27版本的lib。而是自带的那些vlc等等的lib需要2.27.不知道老大能不能给解决下。

**Comment by holazt** [comment]
@fenglelyng 目前的打包环境是 Ubuntu 18.10

**Comment by fenglelyng** [comment]
我试过，把高版本的libc等等放进去，也是没办法使用的，因为和系统不匹配。但是像blender之类的为什么就可以自带libc，我没别的意思，只是想问问，是不是静态和动态问题？？

**Comment by holazt** [comment]
@fenglelyng 与 #1 问题一样，需要打包 libc 进 AppImage，使之具有通用性。libm.so 和 libc.so 是 GNU C 库, 它们都是动态链接库。

**Comment by holazt** [comment]
glibc versions:
 
| Distribution | glibc version |
|--------------|---------------|
| Debian 7     | 2.13          |
| Debian 8     | 2.19          |
| Debian 9     | 2.24          |
| CentOS 6     | 2.12          |
| CentOS 7     | 2.17          |
| Ubuntu 14.04 | 2.19          |
| Ubuntu 16.04 | 2.23          |
| Ubuntu 18.04 | 2.27          |
| openSUSE Leap 15.0 | 2.26          |
| openSUSE Leap 15.1 | 2.26          |
| openSUSE Tumbleweed | 2.29     |

**Comment by holazt** [comment]
@fenglelyng 我会尝试基于 debian 9 来打包，它的 glibc version 是 2.24

**Comment by fenglelyng** [comment]
> @fenglelyng 我会尝试基于 debian 9 来打包，它的 glibc version 是 2.24

好的谢谢你了，因为大部分系统都不会这么激进，像suse15.1到现在还是2.26，而tw就已经用2.29了比ubuntu还新，但是我觉得大部分linux用户都不会太激进

**Comment by holazt** [comment]
可以尝试 https://github.com/ZetaoYang/netease-cloud-music-appimage/releases/tag/1.2.0.3-1. 不再将 libglib2.0 打包进 AppImage, 直接使用系统的。另外也将 libc6 打包进 AppImage 了。
