### ISSUE TITLE
Arch Linux 使用fcitx5无法输入中文

### ISSUE THREAD

**Issue by ghost** [ZetaoYang/netease-cloud-music-appimage#4]
很棒的项目! 但是现在遇到了一个问题，在Arch Linux上使用fcitx5不能在里面打中文

**Comment by holazt** [comment]
@dafeinayius  Please try this one https://github.com/ZetaoYang/netease-cloud-music-appimage/releases/tag/1.2.0.2-2.

**Comment by ghost** [comment]
试了这版，fcitx5还是不可以，fcitx4可以，我也不是很明白，参考[tamlok/vnote/issues/657](https://github.com/tamlok/vnote/issues/657)和https://forum.suse.org.cn/t/topic/12235

**Comment by holazt** [comment]
那就是需要编译一下最新的 [`fcitx5-qt`](https://github.com/fcitx/fcitx5-qt) 了。目前是直接用的 `fcitx-frontend-qt5` 这个包的 1.2.2 版本 (fcitx4)，此包的源码就是 https://github.com/fcitx/fcitx-qt5 。

**Comment by holazt** [comment]
另外，netease-cloud-music 这个网易与深度合作开发的软件，官方目前发布的 deb 支持的 Linux 发行版只有 deepin15 和 ubuntu 18.04 ， 而 `fcitx5-frontend-qt5` 包在 Ubuntu 20.04 里面才首次出现 https://packages.ubuntu.com/focal/libs/fcitx5-frontend-qt5 。

你若想现在直接使用 fctix5 的话， 将 `NetEase_Cloud_Music-1.2.0.2-2.glibc2.17-x86_64.AppImage
 --appimage-extract` 解包，参照 https://ubuntu.pkgs.org/20.04/ubuntu-universe-amd64/fcitx5-frontend-qt5_0.0~git20200118.2e38c95-1build3_amd64.deb.html 这个里面的文件路径 将 .so 库文件放进解包后的那个目录里，尝试 run 一下试试。

**Comment by ghost** [comment]
试着拆开，放了这个包和他依赖包的文件进去，用appimagetool再压好，但是运行不起来，一些库文件的版本不够新，可能相应的包还没找全，有点难弄，暂时放弃了

**Comment by holazt** [comment]
暂时 只支持 fctix4 了，如果网易出 Ubuntu20.04 的 deb 包的话，我会跟进到 fctix5。

**Comment by CoelacanthusHex** [comment]
> 试了这版，fcitx5还是不可以，fcitx4可以，我也不是很明白，参考[tamlok/vnote/issues/657](https://github.com/tamlok/vnote/issues/657)和[forum.suse.org.cn/t/topic/12235](https://forum.suse.org.cn/t/topic/12235)

是否尝试过使用fcitx4的输入法模块使用fcitx5
我记得fcitx5同时支持4和5的输入法模块

**Comment by ghost** [comment]
> > 试了这版，fcitx5还是不可以，fcitx4可以，我也不是很明白，参考[tamlok/vnote/issues/657](https://github.com/tamlok/vnote/issues/657)和[forum.suse.org.cn/t/topic/12235](https://forum.suse.org.cn/t/topic/12235)
> 
> 是否尝试过使用fcitx4的输入法模块使用fcitx5
> 我记得fcitx5同时支持4和5的输入法模块

是这样的，fcitx5模块直接写的fcitx，也不行

**Comment by ZetaoYang** [comment]
fcitx 版本还是跟随 Linux 发行版(当前是 Ubuntu 18.04)，如果 释出了 Ubuntu 20.04 的 netease-cloud-music deb 包的话，我会跟进加入 fcitx5 的支持。

**Comment by holazt** [comment]
可以试试 https://github.com/ZetaoYang/netease-cloud-music-appimage/releases/tag/1.2.0.3-1 ,我在 Fedora 37 KDE fcitx5 rime 是可以输入中文的
