### ISSUE TITLE
希望能够播放无损音乐

### ISSUE THREAD

**Issue by codexvn** [ZetaoYang/netease-cloud-music-appimage#7]
通过对vlc打补丁能够实现无损音乐的播放，是否考虑修复这个bug?
>https://blog.eh5.me/fix-ncm-flac-playing/

**Comment by holazt** [comment]
@codexvn Solved at https://github.com/ZetaoYang/netease-cloud-music-appimage/commit/d594ae4bbfeed3b7fb29e601b6a2cabafbcf279a 
https://github.com/ZetaoYang/netease-cloud-music-appimage/releases/tag/1.2.0.3 NetEase_Cloud_Music-SQ-1.2.0.3.glibc2.28-x86_64.AppImage. I've tested it under fedora 33 gnome wayland.
