### ISSUE TITLE
Debian 11 运行不了

### ISSUE THREAD

**Issue by left3721** [ZetaoYang/netease-cloud-music-appimage#8]
./NetEase_Cloud_Music-SQ-1.2.0.3.glibc2.28-x86_64.AppImage 
netease-cloud-music: symbol lookup error: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_module_open_full

**Comment by holazt** [comment]
与 https://bbs.archlinux.org/viewtopic.php?id=269838 类似，可以先尝试文中提到的方法手工更新一下 Appimage， 我有空更新一下 github release。
Ubuntu 18.04 的 `libglib2.0-0` 版本是 2.56.1 https://ubuntu.pkgs.org/18.04/ubuntu-main-amd64/libglib2.0-0_2.56.1-2ubuntu1_amd64.deb.html ，
Debian 11 是 2.66.8 https://debian.pkgs.org/11/debian-main-amd64/libglib2.0-0_2.66.8-1_amd64.deb.html

**Comment by left3721** [comment]
嗯 ，手动更新已后可以正常使用，发现系统自带的文件管理器，无法动行了。

**Comment by holazt** [comment]
可以试试 https://github.com/ZetaoYang/netease-cloud-music-appimage/releases/tag/1.2.0.3-1. 不再将 libglib2.0 打包进 AppImage, 直接使用系统的。
