### ISSUE TITLE
Ubuntu 22.04 64bit 使用 NetEase_Cloud_Music-SQ-1.2.0.3.glibc2.28-x86_64.AppImage 报错

### ISSUE THREAD

**Issue by Niezhanyang** [ZetaoYang/netease-cloud-music-appimage#9]
Ubuntu 22.04 64bit 使用 NetEase_Cloud_Music-SQ-1.2.0.3.glibc2.28-x86_64.AppImage
步骤如下:
bash下使用
sudo apt install fuse
chmod a+x *.AppImage
./NetEase_Cloud_Music-SQ-1.2.0.3.glibc2.28-x86_64.AppImage

报错：
netease-cloud-music: symbol lookup error: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_module_open_full

**Comment by ZetaoYang** [comment]
我在 Ubuntu 22.04 重新打包上试试，主要是原始 deb 包很旧未更新了，新系统中未必能使用。

**Comment by ZetaoYang** [comment]
我在 Ubuntu 22.04 上重新打包试试，主要是原始 deb 包很久未更新了，新系统中未必能使用。

**Comment by holazt** [comment]
可以试试 https://github.com/ZetaoYang/netease-cloud-music-appimage/releases/tag/1.2.0.3-1 ，不再将 libglib2.0 打包进 AppImage, 直接使用系统的。
